//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ULACIT2021_PAGO_ELECTRONICO_BUSESEntities : DbContext
    {
        public ULACIT2021_PAGO_ELECTRONICO_BUSESEntities()
            : base("name=ULACIT2021_PAGO_ELECTRONICO_BUSESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClienteTarjeta> ClienteTarjeta { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<RutaChofer> RutaChofer { get; set; }
    }
}
