//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int Codigo { get; set; }
        public int ClienteId { get; set; }
        public int RutaId { get; set; }
        public int TarjetaClienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Ruta Ruta { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
